//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasWpfApplication.ServiceCard {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCard.CardSoap")]
    public interface CardSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealFirstTwoPublicCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DealFirstTwoPublicCard(string firstCard, string secondCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealFirstThreePublicCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DealFirstThreePublicCard(string firstCard, string secondCard, string thirdCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealFourthPublicCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DealFourthPublicCard(string fourthCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealFifthPublicCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DealFifthPublicCard(string fifthCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DealPrivateCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DealPrivateCard(int playerID, string firstCard, string secondCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPublicCardForLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPublicCardForLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrivateCardForLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPrivateCardForLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrivateCardByPlayerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPrivateCardByPlayerID(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrivateCardByGameID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPrivateCardByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPublicCardsByGameID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPublicCardsByGameID(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataUploadAPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DataUploadAPI(string card, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataUndoAPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DataUndoAPI(string type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardSoapChannel : TexasWpfApplication.ServiceCard.CardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardSoapClient : System.ServiceModel.ClientBase<TexasWpfApplication.ServiceCard.CardSoap>, TexasWpfApplication.ServiceCard.CardSoap {
        
        public CardSoapClient() {
        }
        
        public CardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool DealFirstTwoPublicCard(string firstCard, string secondCard) {
            return base.Channel.DealFirstTwoPublicCard(firstCard, secondCard);
        }
        
        public bool DealFirstThreePublicCard(string firstCard, string secondCard, string thirdCard) {
            return base.Channel.DealFirstThreePublicCard(firstCard, secondCard, thirdCard);
        }
        
        public bool DealFourthPublicCard(string fourthCard) {
            return base.Channel.DealFourthPublicCard(fourthCard);
        }
        
        public bool DealFifthPublicCard(string fifthCard) {
            return base.Channel.DealFifthPublicCard(fifthCard);
        }
        
        public bool DealPrivateCard(int playerID, string firstCard, string secondCard) {
            return base.Channel.DealPrivateCard(playerID, firstCard, secondCard);
        }
        
        public System.Data.DataSet GetPublicCardForLive() {
            return base.Channel.GetPublicCardForLive();
        }
        
        public System.Data.DataSet GetPrivateCardForLive() {
            return base.Channel.GetPrivateCardForLive();
        }
        
        public System.Data.DataSet GetPrivateCardByPlayerID(int playerID) {
            return base.Channel.GetPrivateCardByPlayerID(playerID);
        }
        
        public System.Data.DataSet GetPrivateCardByGameID(int gameID) {
            return base.Channel.GetPrivateCardByGameID(gameID);
        }
        
        public System.Data.DataSet GetPublicCardsByGameID(int gameID) {
            return base.Channel.GetPublicCardsByGameID(gameID);
        }
        
        public string DataUploadAPI(string card, string type) {
            return base.Channel.DataUploadAPI(card, type);
        }
        
        public string DataUndoAPI(string type) {
            return base.Channel.DataUndoAPI(type);
        }
    }
}
