//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasWpfApplication.ServiceAdministrator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdministrator.AdministratorSoap")]
    public interface AdministratorSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TexasWpfApplication.ServiceAdministrator.HelloWorldResponse HelloWorld(TexasWpfApplication.ServiceAdministrator.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAdministrator", ReplyAction="*")]
        TexasWpfApplication.ServiceAdministrator.CheckAdministratorResponse CheckAdministrator(TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPassword", ReplyAction="*")]
        TexasWpfApplication.ServiceAdministrator.ResetPasswordResponse ResetPassword(TexasWpfApplication.ServiceAdministrator.ResetPasswordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ipAdress 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayerIDForPlayerLogin", ReplyAction="*")]
        TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginResponse GetPlayerIDForPlayerLogin(TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ipAdress 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPlayerIP", ReplyAction="*")]
        TexasWpfApplication.ServiceAdministrator.SetPlayerIPResponse SetPlayerIP(TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TexasWpfApplication.ServiceAdministrator.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TexasWpfApplication.ServiceAdministrator.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAdministratorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAdministrator", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequestBody Body;
        
        public CheckAdministratorRequest() {
        }
        
        public CheckAdministratorRequest(TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckAdministratorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckAdministratorRequestBody() {
        }
        
        public CheckAdministratorRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAdministratorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAdministratorResponse", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.CheckAdministratorResponseBody Body;
        
        public CheckAdministratorResponse() {
        }
        
        public CheckAdministratorResponse(TexasWpfApplication.ServiceAdministrator.CheckAdministratorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckAdministratorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckAdministratorResult;
        
        public CheckAdministratorResponseBody() {
        }
        
        public CheckAdministratorResponseBody(bool CheckAdministratorResult) {
            this.CheckAdministratorResult = CheckAdministratorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPassword", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.ResetPasswordRequestBody Body;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(TexasWpfApplication.ServiceAdministrator.ResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public ResetPasswordRequestBody() {
        }
        
        public ResetPasswordRequestBody(string name, string newPassword) {
            this.name = name;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.ResetPasswordResponseBody Body;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(TexasWpfApplication.ServiceAdministrator.ResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ResetPasswordResult;
        
        public ResetPasswordResponseBody() {
        }
        
        public ResetPasswordResponseBody(bool ResetPasswordResult) {
            this.ResetPasswordResult = ResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerIDForPlayerLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayerIDForPlayerLogin", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequestBody Body;
        
        public GetPlayerIDForPlayerLoginRequest() {
        }
        
        public GetPlayerIDForPlayerLoginRequest(TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayerIDForPlayerLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ipAdress;
        
        public GetPlayerIDForPlayerLoginRequestBody() {
        }
        
        public GetPlayerIDForPlayerLoginRequestBody(string ipAdress) {
            this.ipAdress = ipAdress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerIDForPlayerLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayerIDForPlayerLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginResponseBody Body;
        
        public GetPlayerIDForPlayerLoginResponse() {
        }
        
        public GetPlayerIDForPlayerLoginResponse(TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayerIDForPlayerLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPlayerIDForPlayerLoginResult;
        
        public GetPlayerIDForPlayerLoginResponseBody() {
        }
        
        public GetPlayerIDForPlayerLoginResponseBody(int GetPlayerIDForPlayerLoginResult) {
            this.GetPlayerIDForPlayerLoginResult = GetPlayerIDForPlayerLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPlayerIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPlayerIP", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequestBody Body;
        
        public SetPlayerIPRequest() {
        }
        
        public SetPlayerIPRequest(TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPlayerIPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int playerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ipAdress;
        
        public SetPlayerIPRequestBody() {
        }
        
        public SetPlayerIPRequestBody(int playerID, string ipAdress) {
            this.playerID = playerID;
            this.ipAdress = ipAdress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPlayerIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPlayerIPResponse", Namespace="http://tempuri.org/", Order=0)]
        public TexasWpfApplication.ServiceAdministrator.SetPlayerIPResponseBody Body;
        
        public SetPlayerIPResponse() {
        }
        
        public SetPlayerIPResponse(TexasWpfApplication.ServiceAdministrator.SetPlayerIPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPlayerIPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPlayerIPResult;
        
        public SetPlayerIPResponseBody() {
        }
        
        public SetPlayerIPResponseBody(bool SetPlayerIPResult) {
            this.SetPlayerIPResult = SetPlayerIPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministratorSoapChannel : TexasWpfApplication.ServiceAdministrator.AdministratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministratorSoapClient : System.ServiceModel.ClientBase<TexasWpfApplication.ServiceAdministrator.AdministratorSoap>, TexasWpfApplication.ServiceAdministrator.AdministratorSoap {
        
        public AdministratorSoapClient() {
        }
        
        public AdministratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasWpfApplication.ServiceAdministrator.HelloWorldResponse TexasWpfApplication.ServiceAdministrator.AdministratorSoap.HelloWorld(TexasWpfApplication.ServiceAdministrator.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TexasWpfApplication.ServiceAdministrator.HelloWorldRequest inValue = new TexasWpfApplication.ServiceAdministrator.HelloWorldRequest();
            inValue.Body = new TexasWpfApplication.ServiceAdministrator.HelloWorldRequestBody();
            TexasWpfApplication.ServiceAdministrator.HelloWorldResponse retVal = ((TexasWpfApplication.ServiceAdministrator.AdministratorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasWpfApplication.ServiceAdministrator.CheckAdministratorResponse TexasWpfApplication.ServiceAdministrator.AdministratorSoap.CheckAdministrator(TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequest request) {
            return base.Channel.CheckAdministrator(request);
        }
        
        public bool CheckAdministrator(string name, string password) {
            TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequest inValue = new TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequest();
            inValue.Body = new TexasWpfApplication.ServiceAdministrator.CheckAdministratorRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            TexasWpfApplication.ServiceAdministrator.CheckAdministratorResponse retVal = ((TexasWpfApplication.ServiceAdministrator.AdministratorSoap)(this)).CheckAdministrator(inValue);
            return retVal.Body.CheckAdministratorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasWpfApplication.ServiceAdministrator.ResetPasswordResponse TexasWpfApplication.ServiceAdministrator.AdministratorSoap.ResetPassword(TexasWpfApplication.ServiceAdministrator.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public bool ResetPassword(string name, string newPassword) {
            TexasWpfApplication.ServiceAdministrator.ResetPasswordRequest inValue = new TexasWpfApplication.ServiceAdministrator.ResetPasswordRequest();
            inValue.Body = new TexasWpfApplication.ServiceAdministrator.ResetPasswordRequestBody();
            inValue.Body.name = name;
            inValue.Body.newPassword = newPassword;
            TexasWpfApplication.ServiceAdministrator.ResetPasswordResponse retVal = ((TexasWpfApplication.ServiceAdministrator.AdministratorSoap)(this)).ResetPassword(inValue);
            return retVal.Body.ResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginResponse TexasWpfApplication.ServiceAdministrator.AdministratorSoap.GetPlayerIDForPlayerLogin(TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequest request) {
            return base.Channel.GetPlayerIDForPlayerLogin(request);
        }
        
        public int GetPlayerIDForPlayerLogin(string ipAdress) {
            TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequest inValue = new TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequest();
            inValue.Body = new TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginRequestBody();
            inValue.Body.ipAdress = ipAdress;
            TexasWpfApplication.ServiceAdministrator.GetPlayerIDForPlayerLoginResponse retVal = ((TexasWpfApplication.ServiceAdministrator.AdministratorSoap)(this)).GetPlayerIDForPlayerLogin(inValue);
            return retVal.Body.GetPlayerIDForPlayerLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TexasWpfApplication.ServiceAdministrator.SetPlayerIPResponse TexasWpfApplication.ServiceAdministrator.AdministratorSoap.SetPlayerIP(TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequest request) {
            return base.Channel.SetPlayerIP(request);
        }
        
        public bool SetPlayerIP(int playerID, string ipAdress) {
            TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequest inValue = new TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequest();
            inValue.Body = new TexasWpfApplication.ServiceAdministrator.SetPlayerIPRequestBody();
            inValue.Body.playerID = playerID;
            inValue.Body.ipAdress = ipAdress;
            TexasWpfApplication.ServiceAdministrator.SetPlayerIPResponse retVal = ((TexasWpfApplication.ServiceAdministrator.AdministratorSoap)(this)).SetPlayerIP(inValue);
            return retVal.Body.SetPlayerIPResult;
        }
    }
}
