//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasManager.RecordService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecordService.RecordSoap")]
    public interface RecordSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool NewRecord(int playerNum, int startChips, float firstInterest, float secondInterest, float thirdInterest, float fourthInterest, float fifthInterest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> NewRecordAsync(int playerNum, int startChips, float firstInterest, float secondInterest, float thirdInterest, float fourthInterest, float fifthInterest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FinishRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> FinishRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordsByPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRecordsByPage(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordsByPage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRecordsByPageAsync(int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordForLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRecordForLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordForLive", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRecordForLiveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecordsNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int getRecordsNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRecordsNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getRecordsNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRecordByID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecordByID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRecordByIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteRecord(int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteRecordAsync(int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestartRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RestartRecord(int RecordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestartRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RestartRecordAsync(int RecordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Texas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Texas(string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Texas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TexasAsync(string command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecordSoapChannel : TexasManager.RecordService.RecordSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecordSoapClient : System.ServiceModel.ClientBase<TexasManager.RecordService.RecordSoap>, TexasManager.RecordService.RecordSoap {
        
        public RecordSoapClient() {
        }
        
        public RecordSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecordSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool NewRecord(int playerNum, int startChips, float firstInterest, float secondInterest, float thirdInterest, float fourthInterest, float fifthInterest) {
            return base.Channel.NewRecord(playerNum, startChips, firstInterest, secondInterest, thirdInterest, fourthInterest, fifthInterest);
        }
        
        public System.Threading.Tasks.Task<bool> NewRecordAsync(int playerNum, int startChips, float firstInterest, float secondInterest, float thirdInterest, float fourthInterest, float fifthInterest) {
            return base.Channel.NewRecordAsync(playerNum, startChips, firstInterest, secondInterest, thirdInterest, fourthInterest, fifthInterest);
        }
        
        public bool FinishRecord() {
            return base.Channel.FinishRecord();
        }
        
        public System.Threading.Tasks.Task<bool> FinishRecordAsync() {
            return base.Channel.FinishRecordAsync();
        }
        
        public System.Data.DataSet GetRecords() {
            return base.Channel.GetRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRecordsAsync() {
            return base.Channel.GetRecordsAsync();
        }
        
        public System.Data.DataSet GetRecordsByPage(int page) {
            return base.Channel.GetRecordsByPage(page);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRecordsByPageAsync(int page) {
            return base.Channel.GetRecordsByPageAsync(page);
        }
        
        public System.Data.DataSet GetRecordForLive() {
            return base.Channel.GetRecordForLive();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRecordForLiveAsync() {
            return base.Channel.GetRecordForLiveAsync();
        }
        
        public int getRecordsNumber() {
            return base.Channel.getRecordsNumber();
        }
        
        public System.Threading.Tasks.Task<int> getRecordsNumberAsync() {
            return base.Channel.getRecordsNumberAsync();
        }
        
        public System.Data.DataSet GetRecordByID(int ID) {
            return base.Channel.GetRecordByID(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRecordByIDAsync(int ID) {
            return base.Channel.GetRecordByIDAsync(ID);
        }
        
        public bool DeleteRecord(int recordID) {
            return base.Channel.DeleteRecord(recordID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRecordAsync(int recordID) {
            return base.Channel.DeleteRecordAsync(recordID);
        }
        
        public bool RestartRecord(int RecordID) {
            return base.Channel.RestartRecord(RecordID);
        }
        
        public System.Threading.Tasks.Task<bool> RestartRecordAsync(int RecordID) {
            return base.Channel.RestartRecordAsync(RecordID);
        }
        
        public System.Data.DataSet Texas(string command) {
            return base.Channel.Texas(command);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TexasAsync(string command) {
            return base.Channel.TexasAsync(command);
        }
    }
}
