//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasWpfApplication.ServiceBet {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBet.BetSoap")]
    public interface BetSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDaMangChips", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDaMangChips();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDaMangPlayerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetDaMangPlayerID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXiaoMangPlayerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetXiaoMangPlayerID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewBet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool NewBet(int playerID, string operation, string chipsBet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UndoPreOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UndoPreOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBetForLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBetForLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBetForLive1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBetForLive1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBetByRecordID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBetByRecordID(int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBetInUnfinishedRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllBetInUnfinishedRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextPlayerIDForLive1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetNextPlayerIDForLive1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextPlayerIDForLive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetNextPlayerIDForLive();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BetSoapChannel : TexasWpfApplication.ServiceBet.BetSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BetSoapClient : System.ServiceModel.ClientBase<TexasWpfApplication.ServiceBet.BetSoap>, TexasWpfApplication.ServiceBet.BetSoap {
        
        public BetSoapClient() {
        }
        
        public BetSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BetSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int GetDaMangChips() {
            return base.Channel.GetDaMangChips();
        }
        
        public int GetDaMangPlayerID() {
            return base.Channel.GetDaMangPlayerID();
        }
        
        public int GetXiaoMangPlayerID() {
            return base.Channel.GetXiaoMangPlayerID();
        }
        
        public bool NewBet(int playerID, string operation, string chipsBet) {
            return base.Channel.NewBet(playerID, operation, chipsBet);
        }
        
        public bool UndoPreOperation() {
            return base.Channel.UndoPreOperation();
        }
        
        public System.Data.DataSet GetBetForLive() {
            return base.Channel.GetBetForLive();
        }
        
        public System.Data.DataSet GetBetForLive1() {
            return base.Channel.GetBetForLive1();
        }
        
        public System.Data.DataSet GetBetByRecordID(int recordID) {
            return base.Channel.GetBetByRecordID(recordID);
        }
        
        public System.Data.DataSet GetAllBetInUnfinishedRecord() {
            return base.Channel.GetAllBetInUnfinishedRecord();
        }
        
        public int GetNextPlayerIDForLive1() {
            return base.Channel.GetNextPlayerIDForLive1();
        }
        
        public int GetNextPlayerIDForLive() {
            return base.Channel.GetNextPlayerIDForLive();
        }
    }
}
